Core/Movement: comment unused parameter
/home/runner/work/TrinityCore/TrinityCore/src/server/game/AI/CoreAI/PassiveAI.cpp:82:52: error: unused parameter ‘id’ [-Werror=unused-parameter]
 void CritterAI::MovementInform(uint32 type, uint32 id)
                                             ~~~~~~~^~
compilation terminated due to -Wfatal-errors.